"""empty message

Revision ID: fd4f9cc9d289
Revises: 75032c110120
Create Date: 2022-05-12 20:29:33.192545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd4f9cc9d289'
down_revision = '75032c110120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(length=200), nullable=True))
    op.drop_column('product', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('images', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
