version: "3.8"

services:
  backend:
    build:
      context: .
    environment:
      - AMQP_URL
    command: "python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:  # db should run before backend
      - db

  queue:
    build:
      context: .
    environment:
      - AMQP_URL
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always  # prevent mysql stopping abruptly.
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    volumes:  # store mysql data
      - ".dbdata:/var/lib/mysql"
    ports:
      - "33066:3306"